name: metanextviro
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - nextflow
  - openjdk=21
  - fastqc
  - multiqc
  - fastp
  - flexbar
  - trim-galore
  - megahit
  - spades
  - blast
  - diamond
  - kraken2
  - krona
  - cd-hit
  - quast
  - bowtie2
  - samtools
  - bedtools
  - ete3
  - biopython
  - pandas
  - matplotlib
  - seaborn
  - r-base =4.3.1
  - r-virfinder
  - checkv
  - pip